name: All Builds (Linux, macOS, Windows, Android, IPA, APK, AAB)

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.2
  FLUTTER_VERSION: 3.24.0
  ANDROID_STUDIO_VERSION: 4.1.1

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          # Update package lists
          sudo apt-get update -y

          # Install essential build tools
          sudo apt-get install -y \
            software-properties-common \
            build-essential \
            wget \
            curl \
            git \
            unzip \
            xz-utils

          # Install Ninja build tool
          sudo apt-get install -y ninja-build

          # Install GTK and other desktop development libraries
          sudo apt-get install -y \
            libgtk-3-dev \
            libglu1-mesa \
            mesa-common-dev \
            libx11-dev \
            libxrandr-dev \
            libxi-dev \
            xorg-dev

      - name: Install Android Studio and SDK
        run: |
          # Create directory for Android Studio
          sudo mkdir -p /opt/android-studio

          # Download Android Studio
          wget https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2023.2.1.23/android-studio-2023.2.1.23-linux.tar.gz

          # Extract Android Studio
          sudo tar -xzf android-studio-2023.2.1.23-linux.tar.gz -C /opt/android-studio --strip-components=1

          # Set environment variables
          echo "ANDROID_HOME=/opt/android-studio/bin" >> $GITHUB_ENV
          echo "PATH=$PATH:/opt/android-studio/bin" >> $GITHUB_ENV

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Configure Flutter for Linux
        run: |
          # Enable Linux desktop development
          flutter config --enable-linux-desktop

          # Verify toolchain
          flutter doctor -v

      - name: Flet Build Linux
        run: |
          flutter config --no-analytics
          flet build linux --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build-artifact
          path: build/linux
          if-no-files-found: warn

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Flet Build macOS
        run: |
          flutter config --no-analytics
          flet build macos --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build-artifact
          path: build/macos
          if-no-files-found: warn

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Flet Build Windows
        run: |
          flutter config --no-analytics
          flet build windows --verbose --no-rich-output --build-number=$env:BUILD_NUMBER --build-version=$env:BUILD_VERSION

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-artifact
          path: build/windows
          if-no-files-found: warn

  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          sdk-version: 35
          accept-licenses: true

      - name: Set Android SDK Path
        run: |
          echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
      - name: Install Android SDK Components
        run: |
          yes | sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"

      - name: Install System Dependencies
        run: |
          # Update package lists
          sudo apt-get update -y

          # Install essential build tools
          sudo apt-get install -y \
            software-properties-common \
            build-essential \
            wget \
            curl \
            git \
            unzip \
            xz-utils

          # Install Ninja build tool
          sudo apt-get install -y ninja-build

          # Install GTK and other desktop development libraries
          sudo apt-get install -y \
            libgtk-3-dev \
            libglu1-mesa \
            mesa-common-dev \
            libx11-dev \
            libxrandr-dev \
            libxi-dev \
            xorg-dev

      - name: Install Android Studio and SDK
        run: |
          # Create directory for Android Studio
          sudo mkdir -p /opt/android-studio

          # Download Android Studio
          wget https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2023.2.1.23/android-studio-2023.2.1.23-linux.tar.gz

          # Extract Android Studio
          sudo tar -xzf android-studio-2023.2.1.23-linux.tar.gz -C /opt/android-studio --strip-components=1

          # Set environment variables
          echo "ANDROID_HOME=/opt/android-studio/bin" >> $GITHUB_ENV
          echo "PATH=$PATH:/opt/android-studio/bin" >> $GITHUB_ENV

      - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Flet Build APK
        run: |
          flutter config --no-analytics
          flet build apk --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-build-artifact
          path: build/apk
          if-no-files-found: warn

  build-ipa:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Flet Build IPA
        run: |
          flutter config --no-analytics
          flet build ipa --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ipa-build-artifact
          path: build/ipa
          if-no-files-found: warn
