name: All Builds (Linux, macOS, Windows, Android, IPA, APK, AAB)

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.2
  FLUTTER_VERSION: 3.24.0
  ANDROID_STUDIO_VERSION: 2023.2.1.23
  ANDROID_SDK_VERSION: 35

jobs:
  build-all-platforms:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install System Dependencies
      run: |
        # Update package lists
        sudo apt-get update -y

        # Install essential build tools
        sudo apt-get install -y \
          software-properties-common \
          build-essential \
          wget \
          curl \
          git \
          unzip \
          xz-utils \
          pkg-config

        # Install Linux desktop development dependencies
        sudo apt-get install -y \
          ninja-build \
          libgtk-3-dev \
          libglu1-mesa \
          mesa-common-dev \
          libx11-dev \
          libxrandr-dev \
          libxi-dev \
          xorg-dev \
          clang \
          cmake \
          libc++-dev

    - name: Setup Android SDK and Tools
      uses: android-actions/setup-android@v3
      with:
        sdk-version: ${{ env.ANDROID_SDK_VERSION }}
        accept-licenses: true

    - name: Install Android Studio and Additional SDK Components
      run: |
        # Create directory for Android Studio
        sudo mkdir -p /opt/android-studio

        # Download Android Studio
        wget https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2023.2.1.23/android-studio-2023.2.1.23-linux.tar.gz

        # Extract Android Studio
        sudo tar -xzf android-studio-2023.2.1.23-linux.tar.gz -C /opt/android-studio --strip-components=1

        # Set environment variables
        echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "PATH=$PATH:$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_ENV

        # Install additional SDK components
        sdkmanager "platform-tools" "platforms;android-${{ env.ANDROID_SDK_VERSION }}"

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Configure Flutter and Development Environments
      run: |
        # Enable desktop and web development
        flutter config --enable-linux-desktop
        flutter config --enable-macos-desktop
        flutter config --enable-windows-desktop
        flutter config --no-analytics
        
        # Verify toolchain
        flutter doctor -v

    - name: Build Linux Desktop
      run: |
        flet build linux --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION

    - name: Build Android APK
      run: |
        flet build apk --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION

    - name: Build Windows Desktop
      run: |
        flet build windows --verbose --no-rich-output --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION

    - name: Build macOS Desktop
      run: |
        flet build macos --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION

    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-build-artifact
        path: build/linux
        if-no-files-found: warn

    - name: Upload Android APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk-artifact
        path: build/apk
        if-no-files-found: warn

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-build-artifact
        path: build/windows
        if-no-files-found: warn

    - name: Upload macOS Artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-build-artifact
        path: build/macos
        if-no-files-found: warn
