name: Build APK for Flet App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet buildozer

      - name: Prepare Buildozer Configuration
        run: |
          echo "Creating buildozer.spec file..."
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi
          sed -i 's/^# (android\.requirements).*/\1 = python3,kivy,flet/' buildozer.spec
          sed -i 's/^# (title =).*/\1 MyFletApp/' buildozer.spec
          sed -i 's/^# (package.name =).*/\1 myfletapp/' buildozer.spec
          sed -i 's/^# (package.domain =).*/\1 org.example/' buildozer.spec

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: flet-app-apk
          path: bin/*.apk
